import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tenzies Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="w-[50%] h-[89%] absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 outer--border border-8 border-black bg-black">
          <div className="w-[90%] h-[86%] absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 outer--border border-8 border-black rounded-2xl box-content bg-gray-200"></div>
        </div>
      </main>
    </div>
  );
}
